### ISSUE TITLE
Should the gateway work under ubuntu 15.10 ?

### ISSUE THREAD

**Issue by mgiaco** [homewsn/whsnbg#5]
Hello,

I tried whsnbg on ubuntu today, but i cannot get it to work. Can you give a littel example on how to use it in the right way?

thx for your help

**Comment by homewsn** [comment]
What kind of difficulties do you get? I built and ran whsnbg on ubuntu 12.04 without problem.

**Comment by mgiaco** [comment]
I followed these steps..

$ curl -L https://github.com/homewsn/whsnbg/archive/v1.2.tar.gz | tar zx
$ cd whsnbg-1.2
$ make
$ sudo make install
$ whsnbg

make && make install => works 
but if I start whsnbg I didn´t get any error. But I do not find any running process. So how to configure it or how can I find out if the broker is running.

What mqtt-sn clients are you using? 

thanks
mathias

**Comment by homewsn** [comment]
You can check MQTT broker first. To do it:
1. Replace `eth0` in the `mqtt_iface = eth0` line of the [res/whsnbg.conf](https://github.com/homewsn/whsnbg/blob/master/res/whsnbg.conf#L6) file with the network interface you want to use (if it's needed).
2. Make new build with enabled detailed log messages: `$ make DETAILED_LOG=1`.
3. Install new build: `$ make install`.
4. Run: `$ whsnbg`.
5. Run the browser and open online free [Websocket MQTT javascript client](http://www.hivemq.com/demos/websocket-client/).
6. Type an IP address of your network interface in the `Host` edit box, `8082` in the `Port` one and push the `Connect` button.

If all goes well, you will see the lines (in the terminal window) like that:

```
eth0: x.x.x.x
eth0: x.x.x.x
>MQTT_CONNECT
<MQTT_CONNACK
```

**Comment by mgiaco** [comment]
Okay thanks, I will try it this weekend. I was on holyday.

thx
