### ISSUE TITLE
what firmwares to use?

### ISSUE THREAD

**Issue by greyltc** [homewsn/whsnbg#7]
Hello, thanks very much for what looks like a really cool project! I'm excited to get started with it. I have a CC2531USB dongle and a few CC2650SensorTags.

Could you please point me to the firmware files I should flash onto these things in order to use them with your gateway?

**Comment by homewsn** [comment]
All sensor and actuator nodes are based on TI CC2530 SOC. The main reason is the low price and wide availability of the CC2530 modules. CC2530 has 8051 MCU and is not compatible with CC2650 (ARM Cortex M3). So you can't flash CC2530 firmware onto CC2650 SensorTag.

**Comment by greyltc** [comment]
Do you see any reason why I couldn't adapt the existing source for the CC2530 firmware to be able to build firmware for my CC2650 tags that's compatible with your project here?

**Comment by homewsn** [comment]
Two reasons at least:
1. Firmware source code for CC2530 modules is not planned to be released to the public at the nearest future. Electrical diagrams and compiled firmware binary code will be published as soon as they will be ready.
2. Source code for CC2530 modules includes inline assembly code, specific for CC2530/CC2531 SOCs only, so I can't build it to use for ARM.

**Comment by greyltc** [comment]
I assume the CC2530 nodes you have working now talk to the CC2531 usb dongle at the base station via some open RF standard (ZigBee or 6LoWPAN) which my SensorTag hardware supports. Would you be willing to share with me the info I'd need to write my own SensorTag firmware from scratch which would work with your existing CC2531 dongle firmware and software stacks?

**Comment by homewsn** [comment]
The network topology is shown [here](http://homewsn.com/). Click the appropriate connection label to learn more.

To ensure the radio compatibility level with CC2531 dongle (needs your own sensor firmware), the following protocol stack needs to be implement (click the WPAN connection label):
- MQTT-SN
- UDP
- IPv4
- Contiki Rime
- IEEE 802.15.4 with 128-bit AES encryption

Wireshark screenshot:
![radio-protocol-stack](https://cloud.githubusercontent.com/assets/8708168/13946624/c2cb64be-f026-11e5-9d78-74a8bab9f2ae.png)

It is much easier to realize the compatibility only with whsnbg (needs your own sensor and border-router firmware). The protocol stack (click the USB connection label):
- MQTT-SN
- UDP
- IPv4

Wireshark screenshot:
![slip-protocol-stack](https://cloud.githubusercontent.com/assets/8708168/13946630/cbb01db8-f026-11e5-896e-92821fa653fe.png)

MQTT-SN connection procedure itself (between sensors and whsnbg) is shown [here](https://github.com/homewsn/whsnbg/wiki/Sensors-connection-procedures).

**Comment by greyltc** [comment]
Great. Thanks for giving me something to start with, but I'm back to the original question:

Where can I find the firmware file to flash into my CC2531USB dongle to test my sensor node firmware against?

**Comment by homewsn** [comment]
You can not download firmware at the present. As I wrote above, electrical diagrams and compiled firmware binary code will be published as soon as they will be ready. But you can always start training with the official [Contiki OS](http://www.contiki-os.org/) examples. They include border-router, cc2531-usb-demo etc. Issue #4 may help you too.

**Comment by greyltc** [comment]
Would you mind explaining what's going on here? Is this something you're intending to commercialize? Why is the firmware development a secret?
