### ISSUE TITLE
trying to create some rules

### ISSUE THREAD

**Issue by krital** [homewsn/whsnbg#8]
would it be possible to provide an example whsnbg.rules file?

**Comment by homewsn** [comment]
[WebUI](https://github.com/homewsn/homewsn.webui) is used to create and edit whsnbg.rules file.
You can play with online demo of the rules editor here: [https://homewsn.github.io/editor.html](https://homewsn.github.io/editor.html)
Then select RulesEditor->Export and see the contents of the whsnbg.rules file.

Unfortunately, I do not yet have a detailed description of the whsnbg.rules file specification.
